export const DASHBOARD_PUBLIC_IDS = Object.freeze({
  view: 'view-inicio',
  root: 'dash',
  hero: 'dash-hero',
  heroGreeting: 'dash-hero-greeting',
  heroSummary: 'dash-hero-summary',
  heroCta: 'dash-hero-cta',
  heroCtaLabel: 'dash-hero-cta-label',
  heroSecondaryCta: 'dash-hero-cta-secondary',
  heroSecondaryCtaLabel: 'dash-hero-cta-secondary-label',
  empty: 'dash-empty',
  onboarding: 'dash-onboarding',
  overflowBanner: 'dash-overflow-banner',
  kpiRoot: 'dash-kpis-root',
  kpiAtivos: 'dash-kpi-ativos',
  kpiAtivosSub: 'dash-kpi-ativos-sub',
  kpiEficiencia: 'dash-kpi-ef',
  kpiEficienciaSub: 'dash-kpi-ef-sub',
  kpiEficienciaSpark: 'dash-kpi-ef-spark',
  kpiAnomalias: 'dash-kpi-anom',
  kpiAnomaliasSub: 'dash-kpi-anom-sub',
  kpiMes: 'dash-kpi-mes',
  kpiMesSub: 'dash-kpi-mes-sub',
  kpiMesSpark: 'dash-kpi-mes-spark',
  nextActionCard: 'dash-next-action-card',
  nextActionTitle: 'dash-next-title',
  nextActionSubtitle: 'dash-next-sub',
  nextActionCta: 'dash-next-cta',
  nextActionCtaLabel: 'dash-next-cta-label',
  lastServiceCard: 'dash-last-service',
  lastServiceTitle: 'dash-last-title',
  lastServiceSubtitle: 'dash-last-sub',
  proOpsRow: 'dash-pro-ops-row',
  criticalAlertsTitle: 'dash-critical-alerts-title',
  criticalAlertsSubtitle: 'dash-critical-alerts-sub',
  criticalAlertsList: 'dash-critical-alerts-list',
  riskClientsTitle: 'dash-risk-clients-title',
  riskClientsSubtitle: 'dash-risk-clients-sub',
  riskClientsList: 'dash-risk-clients-list',
  monthSection: 'dash-month-section',
  monthLabel: 'dash-month-label',
  monthServices: 'dash-month-services',
  monthEquipments: 'dash-month-equips',
  monthPending: 'dash-month-pending',
  monthTrend: 'dash-month-trend',
  readOnlyBlocksRoot: 'dash-readonly-blocks-root',
  criticalSection: 'dash-critical-section',
  criticalNow: 'dash-critical-now',
  criticalNowCount: 'dash-critical-now-count',
  alertsSection: 'dash-alerts-section',
  alertsMini: 'dash-alertas-mini',
  upgradeInlineHint: 'dash-upgrade-inline-hint',
  criticosSection: 'dash-criticos-section',
  criticos: 'dash-criticos',
  recentesSection: 'dash-recentes-section',
  recentes: 'dash-recentes',
  chartStatusPie: 'chart-status-pie',
  chartTrendLine: 'chart-trend-line',
  chartTiposDoughnut: 'chart-tipos-doughnut',
});

export const DASHBOARD_ACTIONS = Object.freeze({
  openModal: 'open-modal',
  goRegisterEquip: 'go-register-equip',
  viewEquip: 'view-equip',
  continueDraft: 'continue-draft',
  discardDraft: 'discard-draft',
});

export const DASHBOARD_PUBLIC_CLASSES = Object.freeze([
  'dash',
  'dash--quick',
  'dash__hero',
  'dash__hero--quick',
  'dash__hero-body',
  'dash__hero-greeting',
  'dash__hero-summary',
  'dash__hero-cta-wrap',
  'dash__hero-cta',
  'dash__hero-cta--secondary',
  'dash__hero-cta-label',
  'dash__empty',
  'dash__kpi-grid',
  'dash__kpi',
  'dash__kpi-label',
  'dash__kpi-value',
  'dash__kpi-sub',
  'dash__card',
  'dash__card--next-action',
  'dash__card--last-service',
  'dash__card-cta',
  'dash__section',
  'dash__section-header',
  'dash__section-label',
  'dash__section-count',
  'dash__analise',
  'dash__accordion',
  'dash__accordion-item',
  'dash__continue-card',
  'alert-card',
  'critical-now-item',
  'recent-card',
]);

export const DASHBOARD_DATA_ATTRIBUTES = Object.freeze([
  'data-tier',
  'data-tone',
  'data-action',
  'data-id',
  'data-nav',
]);
