export const DASHBOARD_PUBLIC_IDS = Object.freeze({
  view: 'view-inicio',
  root: 'dash',
  hero: 'dash-hero',
  heroGreeting: 'dash-hero-greeting',
  heroSummary: 'dash-hero-summary',
  heroCta: 'dash-hero-cta',
  heroCtaLabel: 'dash-hero-cta-label',
  heroSecondaryCta: 'dash-hero-cta-secondary',
  heroSecondaryCtaLabel: 'dash-hero-cta-secondary-label',
  empty: 'dash-empty',
  onboarding: 'dash-onboarding',
  proDraftRoot: 'dash-pro-draft-root',
  overflowBanner: 'dash-overflow-banner',
  kpiRoot: 'dash-kpis-root',
  kpiAtivos: 'dash-kpi-ativos',
  kpiAtivosSub: 'dash-kpi-ativos-sub',
  kpiEficiencia: 'dash-kpi-ef',
  kpiEficienciaSub: 'dash-kpi-ef-sub',
  kpiEficienciaSpark: 'dash-kpi-ef-spark',
  kpiAnomalias: 'dash-kpi-anom',
  kpiAnomaliasSub: 'dash-kpi-anom-sub',
  kpiMes: 'dash-kpi-mes',
  kpiMesSub: 'dash-kpi-mes-sub',
  kpiMesSpark: 'dash-kpi-mes-spark',
  nextActionCard: 'dash-next-action-card',
  nextActionTitle: 'dash-next-title',
  nextActionSubtitle: 'dash-next-sub',
  nextActionCta: 'dash-next-cta',
  nextActionCtaLabel: 'dash-next-cta-label',
  lastServiceCard: 'dash-last-service',
  lastServiceTitle: 'dash-last-title',
  lastServiceSubtitle: 'dash-last-sub',
  proOpsRow: 'dash-pro-ops-row',
  criticalAlertsCard: 'dash-critical-alerts-card',
  criticalAlertsTitle: 'dash-critical-alerts-title',
  criticalAlertsSubtitle: 'dash-critical-alerts-sub',
  criticalAlertsList: 'dash-critical-alerts-list',
  riskClientsCard: 'dash-risk-clients-card',
  riskClientsTitle: 'dash-risk-clients-title',
  riskClientsSubtitle: 'dash-risk-clients-sub',
  riskClientsList: 'dash-risk-clients-list',
  monthSection: 'dash-month-section',
  monthLabel: 'dash-month-label',
  monthServices: 'dash-month-services',
  monthEquipments: 'dash-month-equips',
  monthPending: 'dash-month-pending',
  monthTrend: 'dash-month-trend',
  readOnlyBlocksRoot: 'dash-readonly-blocks-root',
  criticalSection: 'dash-critical-section',
  criticalNow: 'dash-critical-now',
  criticalNowCount: 'dash-critical-now-count',
  alertsSection: 'dash-alerts-section',
  alertsMini: 'dash-alertas-mini',
  upgradeInlineHint: 'dash-upgrade-inline-hint',
  criticosSection: 'dash-criticos-section',
  criticos: 'dash-criticos',
  recentesSection: 'dash-recentes-section',
  recentes: 'dash-recentes',
  chartStatusPie: 'chart-status-pie',
  chartTrendLine: 'chart-trend-line',
  chartTiposDoughnut: 'chart-tipos-doughnut',
});

export const DASHBOARD_ACTIONS = Object.freeze({
  openModal: 'open-modal',
  startServiceRegistration: 'start-service-registration',
  goRegisterEquip: 'go-register-equip',
  onboardingDismiss: 'onboarding-dismiss',
  contextualOnboardingRegister: 'contextual-onboarding-register',
  contextualOnboardingClientes: 'contextual-onboarding-clientes',
  contextualOnboardingSkip: 'contextual-onboarding-skip',
  openUpgrade: 'open-upgrade',
  viewEquip: 'view-equip',
  continueDraft: 'continue-draft',
  discardDraft: 'discard-draft',
});

export const DASHBOARD_PUBLIC_CLASSES = Object.freeze([
  'dash',
  'dash--quick',
  'dash__hero',
  'dash__hero--quick',
  'dash__hero-body',
  'dash__hero-greeting',
  'dash__hero-summary',
  'dash__hero-cta-wrap',
  'dash__hero-cta',
  'dash__hero-cta--secondary',
  'dash__hero-cta-label',
  'dash__empty',
  'empty-state',
  'empty-state__icon',
  'empty-state__title',
  'empty-state__sub',
  'empty-state__cta',
  'onb-card',
  'onb-card__head',
  'onb-card__title',
  'onb-card__sub',
  'onb-card__close',
  'onb-card__progress',
  'onb-card__steps',
  'onb-step',
  'contextual-onboarding',
  'contextual-onboarding__actions',
  'onboarding-banner',
  'onboarding-banner__icon',
  'onboarding-banner__title',
  'onboarding-banner__desc',
  'dash-overflow-banner',
  'dash-overflow-banner__icon',
  'dash-overflow-banner__text',
  'dash-overflow-banner__cta',
  'btn',
  'btn--primary',
  'btn--sm',
  'dash__kpi-grid',
  'dash__kpi',
  'dash__kpi-label',
  'dash__kpi-value',
  'dash__kpi-sub',
  'dash__pair',
  'dash__card',
  'dash__card--next-action',
  'dash__card--last-service',
  'dash__card-label',
  'dash__card-title',
  'dash__card-sub',
  'dash__card-desc',
  'dash__card-cta',
  'dash__section',
  'dash__section-header',
  'dash__section-label',
  'dash__section-count',
  'dash__analise',
  'dash__accordion',
  'dash__accordion-item',
  'dash__accordion-summary',
  'dash__accordion-title',
  'dash__accordion-chev',
  'dash__accordion-body',
  'dash__continue-card',
  'dash__continue-card__icon',
  'dash__continue-card__body',
  'dash__continue-card__title',
  'dash__continue-card__sub',
  'dash__continue-card__cta',
  'dash__continue-card__close',
  'alert-card',
  'critical-now-item',
  'recent-card',
]);

export const DASHBOARD_DATA_ATTRIBUTES = Object.freeze([
  'data-tier',
  'data-tone',
  'data-action',
  'data-id',
  'data-nav',
  'data-upgrade-source',
  'data-highlight-plan',
  'data-limit-type',
]);
