export const REGISTRO_PUBLIC_IDS = Object.freeze({
  view: 'view-registro',
  headerRoot: 'registro-header-root',
  hero: 'registro-hero',
  heroSub: 'registro-hero-sub',
  heroPillText: 'registro-hero-pill-text',
  heroMeter: 'registro-hero-meter',
  progressCount: 'form-progress-count',
  equipTrigger: 'r-equip-trigger',
  equipName: 'r-equip-name',
  equipMeta: 'r-equip-meta',
  equipSelect: 'r-equip',
  datetimeWrap: 'registro-datetime-wrap',
  dateNowButton: 'r-data-now-btn',
  dateNowLabel: 'r-data-now-label',
  dateEditButton: 'r-data-edit-btn',
  dateInput: 'r-data',
  typeSelect: 'r-tipo',
  typeCustomWrap: 'r-tipo-custom-wrap',
  typeCustomInput: 'r-tipo-custom',
  obs: 'r-obs',
  technicianInput: 'r-tecnico',
  contextCard: 'registro-context-card',
  contextCliente: 'registro-context-cliente',
  contextSetor: 'registro-context-setor',
  contextEquip: 'registro-context-equip',
  contextHint: 'registro-context-hint',
  clienteDetails: 'registro-cliente-details',
  clienteContextSummary: 'registro-cliente-context-summary',
  clienteNome: 'r-cliente-nome',
  clienteDocumento: 'r-cliente-documento',
  clienteContato: 'r-cliente-contato',
  localAtendimento: 'r-local-atendimento',
  pecas: 'r-pecas',
  custoPecas: 'r-custo-pecas',
  custoMaoObra: 'r-custo-mao-obra',
  photoDropZone: 'photo-drop-zone',
  photoDropText: 'photo-drop-text',
  inputFotos: 'input-fotos',
  inputFotosCamera: 'input-fotos-camera',
  photoPreview: 'photo-preview',
  photosRoot: 'registro-photos-root',
  impactTitle: 'registro-impact-title',
  impactSubtitle: 'registro-impact-subtitle',
  impactHint: 'registro-impact-hint',
  prioridade: 'r-prioridade',
  status: 'r-status',
  proxima: 'r-proxima',
  checklistDetails: 'r-checklist-details',
  checklistPri: 'r-checklist-pri',
  checklistSummary: 'r-checklist-summary',
  checklistBody: 'r-checklist-body',
  checklistUpsell: 'r-checklist-upsell',
  signatureHint: 'registro-signature-hint',
  actionAnchor: 'tour-signature-anchor',
});

export const REGISTRO_ACTIONS = Object.freeze({
  save: 'save-registro',
  clear: 'clear-registro',
  quickTemplate: 'quick-service-template',
  checklistSet: 'r-checklist-set',
  checklistMeasure: 'r-checklist-measure',
  checklistObs: 'r-checklist-obs',
  signatureCapture: 'registro-signature-capture',
  signatureOpen: 'registro-signature-open',
  signatureRemove: 'registro-signature-remove',
  signatureUpsell: 'signature-upsell-cta',
  photoOpen: 'registro-photo-open',
  photoRemove: 'registro-photo-remove',
});

export const REGISTRO_DATA_ATTRIBUTES = Object.freeze([
  'data-action',
  'data-r-action',
  'data-template',
  'data-color',
  'data-item',
  'data-item-id',
  'data-status',
  'data-unit',
  'data-state',
]);

export const REGISTRO_PUBLIC_CLASSES = Object.freeze([
  'registro-hero',
  'registro-hero__pill',
  'registro-hero__meter',
  'registro-quick',
  'registro-quick__tile',
  'registro-field',
  'registro-field__label',
  'registro-field__input',
  'registro-field__select',
  'registro-details',
  'registro-details__body',
  'registro-actions',
  'registro-context-card',
  'registro-photo-quick',
  'registro-sig-hint',
  'r-checklist__body',
  'r-checklist__row',
  'r-checklist__status',
  'r-checklist__measure-input',
  'r-checklist__obs',
]);

export const REGISTRO_REACT_ROOTS = Object.freeze({
  header: REGISTRO_PUBLIC_IDS.headerRoot,
  checklist: REGISTRO_PUBLIC_IDS.checklistBody,
  photos: REGISTRO_PUBLIC_IDS.photosRoot,
  signature: REGISTRO_PUBLIC_IDS.signatureHint,
});

export const REGISTRO_FIELD_IDS = Object.freeze([
  REGISTRO_PUBLIC_IDS.equipSelect,
  REGISTRO_PUBLIC_IDS.dateInput,
  REGISTRO_PUBLIC_IDS.typeSelect,
  REGISTRO_PUBLIC_IDS.typeCustomInput,
  REGISTRO_PUBLIC_IDS.obs,
  REGISTRO_PUBLIC_IDS.technicianInput,
  REGISTRO_PUBLIC_IDS.status,
  REGISTRO_PUBLIC_IDS.prioridade,
  REGISTRO_PUBLIC_IDS.proxima,
  REGISTRO_PUBLIC_IDS.pecas,
  REGISTRO_PUBLIC_IDS.custoPecas,
  REGISTRO_PUBLIC_IDS.custoMaoObra,
  REGISTRO_PUBLIC_IDS.clienteNome,
  REGISTRO_PUBLIC_IDS.clienteDocumento,
  REGISTRO_PUBLIC_IDS.clienteContato,
  REGISTRO_PUBLIC_IDS.localAtendimento,
]);

export const REGISTRO_MODES = Object.freeze({
  create: 'create',
  edit: 'edit',
});

export const REGISTRO_PROGRESS_FIELD_IDS = Object.freeze([
  REGISTRO_PUBLIC_IDS.equipSelect,
  REGISTRO_PUBLIC_IDS.dateInput,
  REGISTRO_PUBLIC_IDS.typeSelect,
  REGISTRO_PUBLIC_IDS.technicianInput,
  REGISTRO_PUBLIC_IDS.obs,
]);

export const REGISTRO_QUICK_TEMPLATES = Object.freeze([
  'limpeza',
  'recarga_gas',
  'troca_filtro',
  'inspecao',
  'manutencao_corretiva',
]);
