export const RELATORIO_PUBLIC_IDS = Object.freeze({
  view: 'view-relatorio',
  mainTitle: 'rel-main-title',
  mainSubtitle: 'rel-main-subtitle',
  modeSegmentSlot: 'rel-mode-segment-slot',
  hero: 'rel-hero',
  heroTitle: 'rel-hero-title',
  filters: 'rel-filters',
  filtersChips: 'rel-filters-chips',
  filtersAdvanced: 'rel-filters-advanced',
  equipSelect: 'rel-equip',
  dateFrom: 'rel-de',
  dateTo: 'rel-ate',
  companyPmocSlot: 'rel-company-pmoc-slot',
  body: 'relatorio-corpo',
  pdfQuotaSlot: 'pdf-quota-slot',
  exportDropdown: 'rel-export-dd',
  exportDropdownToggle: 'btn-export-dd-toggle',
  exportDropdownMenu: 'rel-export-dd-menu',
  pmocMain: 'rel-dd-pmoc-main',
  pmocInfo: 'rel-dd-pmoc-info',
  pmocNudge: 'rel-dd-pmoc-nudge',
});

export const RELATORIO_ACTIONS = Object.freeze({
  whatsappExport: 'whatsapp-export',
  exportPdf: 'export-pdf',
  toggleExportDropdown: 'toggle-export-dd',
  openPmocModal: 'open-pmoc-modal',
  openPmocInfo: 'open-pmoc-info',
  toggleAdvanced: 'rel-toggle-advanced',
  clearFilters: 'rel-clear-filters',
  viewSignature: 'rel-view-signature',
  toggleCard: 'rel-toggle-card',
});

export const RELATORIO_NAV_TARGETS = Object.freeze({
  historico: 'historico',
  relatorio: 'relatorio',
  registro: 'registro',
  clientes: 'clientes',
  pricing: 'pricing',
});

export const RELATORIO_DATA_ATTRIBUTES = Object.freeze([
  'data-action',
  'data-rel-action',
  'data-nav',
  'data-id',
  'data-view-mode',
  'data-tier',
]);

export const RELATORIO_PUBLIC_CLASSES = Object.freeze([
  'servicos-toggle',
  'servicos-toggle__btn',
  'rel-toolbar',
  'rel-toolbar__actions',
  'rel-toolbar__btn',
  'rel-toolbar__quota-slot',
  'rel-export-dd',
  'rel-export-dd__menu',
  'rel-export-dd__item',
  'rel-title',
  'rel-subtitle',
  'rel-hero',
  'rel-hero__brand',
  'rel-hero__title',
  'rel-hero__meta',
  'rel-hero__narrative',
  'rel-hero__kpis',
  'rel-kpi',
  'rel-kpi__row',
  'rel-kpi__icon',
  'rel-kpi__value',
  'rel-kpi__label',
  'rel-segmented',
  'rel-segmented__opt',
  'rel-mode-segment',
  'rel-mode-segment__item',
  'rel-filters',
  'rel-filters__chips',
  'rel-filters__advanced',
  'rel-chip',
  'rel-chip__clear',
  'rel-company-pmoc',
  'rel-proximas__item',
  'rel-corretivas-banner',
  'rel-records',
  'rel-record',
  'rel-record__head',
  'rel-record__title',
  'rel-record__meta',
  'rel-record__toggle',
  'rel-record__details',
  'rel-record__section',
  'rel-spec',
  'rel-status',
  'rel-tipo-icon',
  'rel-sigthumb',
  'rel-empty',
  'rel-empty__cta',
]);

export const RELATORIO_VIEW_MODES = Object.freeze({
  compact: 'compact',
  detailed: 'detailed',
});

export const RELATORIO_PLAN_CODES = Object.freeze({
  pro: 'pro',
});
