import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

describe('internal visual identity tokens', () => {
  it('defines the dark operational token foundation for the authenticated app', () => {
    const tokens = readFileSync('src/assets/styles/tokens.css', 'utf8');
    const redesign = readFileSync('src/assets/styles/redesign.css', 'utf8');

    expect(tokens).toContain('--ct-app-bg: #26282b;');
    expect(tokens).toContain('--ct-surface: #353941;');
    expect(tokens).toContain('--ct-surface-raised: #3e434d;');
    expect(tokens).toContain('--ct-surface-subtle: #2d3036;');
    expect(tokens).toContain('--ct-border: rgba(144, 184, 248, 0.16);');
    expect(tokens).toContain('--ct-border-strong: rgba(144, 184, 248, 0.28);');
    expect(tokens).toContain('--ct-brand: #5f85db;');
    expect(tokens).toContain('--ct-brand-hover: #90b8f8;');
    expect(tokens).toContain('--ct-text: #f4f7fb;');
    expect(tokens).toContain('--ct-text-muted: #c7d0e0;');
    expect(tokens).toContain('--ct-text-faint: #98a4b8;');
    expect(tokens).toContain('--ct-shadow-soft: 0 18px 48px rgba(0, 0, 0, 0.28);');
    expect(tokens).toContain('--ct-success: #4ade80;');
    expect(tokens).toContain('--ct-info: #90b8f8;');
    expect(tokens).toContain('--ct-warn: #fbbf24;');
    expect(tokens).toContain('--ct-error: #fb7185;');
    expect(tokens).toContain('--bg: var(--ct-app-bg);');
    expect(tokens).toContain('--surface: var(--ct-surface);');
    expect(tokens).toContain('--card-hover: var(--ct-surface-raised);');
    expect(tokens).toContain('--primary: var(--ct-brand);');
    expect(tokens).toContain('--primary-strong: var(--ct-brand-hover);');
    expect(tokens).toContain('--text: var(--ct-text);');
    expect(tokens).toContain('--muted: var(--ct-text-muted);');
    expect(tokens).toContain('--muted-light: var(--ct-text-faint);');
    expect(tokens).toContain('--neon-cyan: var(--ct-brand);');
    expect(tokens).toContain('--neon-red: var(--ct-error);');
    expect(redesign).toContain('var(--ct-app-bg)');
    expect(redesign).toContain('var(--ct-surface) 0%, var(--ct-surface-subtle) 100%');
    expect(redesign).toContain('var(--ct-brand-hover), var(--ct-brand)');
    expect(redesign).toContain('var(--ct-gold-soft)');
    expect(redesign).toContain('.app-shell--with-sidebar .app-sidebar__brand');
    expect(redesign).toContain('PR 3 — Shared controls token foundation');
    expect(redesign).toContain('#app:not(.landing-active) .btn--primary');
    expect(redesign).toContain('background: var(--ct-brand) !important;');
    expect(redesign).toContain('#app:not(.landing-active) .form-control');
    expect(redesign).toContain('box-shadow: 0 0 0 3px rgba(144, 184, 248, 0.22) !important;');
    expect(redesign).toContain('#app:not(.landing-active) .badge--ok');
    expect(redesign).toContain('background: var(--ct-success-soft) !important;');
    expect(redesign).toContain('#app:not(.landing-active) .empty-state');
    expect(redesign).toContain('body:not(.landing-active) .modal-overlay');
    expect(redesign).toContain('PR 4 - Dashboard operational dark refresh');
    expect(redesign).toContain('#app:not(.landing-active) #dash');
    expect(redesign).toContain('--dsh-accent: var(--ct-brand);');
    expect(redesign).toContain('--dsh-card-bg: var(--ct-surface);');
    expect(redesign).toContain('#app:not(.landing-active) #dash .dash__hero');
    expect(redesign).toContain('#app:not(.landing-active) #dash .dash__kpi');
    expect(redesign).toContain('#app:not(.landing-active) #dash .onb-card');
    expect(redesign).toContain('#app:not(.landing-active) #dash .dash-overflow-banner');
    expect(redesign).not.toContain('linear-gradient(135deg, #f6c85f 0%, #d79b36 100%)');
    expect(redesign).not.toMatch(/Ver demonstra[çc][ãa]o/i);
  });
});
