export const HEADER_PUBLIC_IDS = Object.freeze({
  root: 'app-header',
  logoPill: 'app-logo-pill',
  logoPillText: 'app-logo-pill-text',
  syncStatus: 'sync-status',
  syncStatusText: 'sync-status-txt',
  alertPill: 'header-alert-pill',
  alertTooltip: 'header-alert-tooltip',
  helpButton: 'header-help-btn',
  helpMenu: 'header-help-menu',
  helpAlertBadge: 'header-help-menu-alert-badge',
  helpGoClientes: 'header-help-go-clientes',
  helpClientesUpsell: 'header-help-clientes-upsell',
  avatar: 'header-avatar',
  avatarInitials: 'header-avatar-initials',
  statsBarInner: 'stats-bar-inner',
  statsTotal: 'hst-total',
  statsMes: 'hst-mes',
  statsAlert: 'hst-alert',
  statusSistema: 'status-sistema',
  statusFalhas: 'status-falhas',
  statusFalhasText: 'status-falhas-txt',
  date: 'hdr-date',
});

export const HEADER_PUBLIC_CLASSES = Object.freeze([
  'app-header',
  'app-header__top',
  'app-logo',
  'app-logo__icon',
  'app-logo__name',
  'app-logo__pill',
  'app-logo__pill-icon',
  'app-logo__pill-text',
  'app-header__actions',
  'header-sync',
  'header-sync__icon',
  'header-sync__text',
  'header-icon-btn',
  'header-alert-btn',
  'header-alert-pill',
  'header-alert-tooltip',
  'header-settings',
  'header-help-menu',
  'header-help-menu__top-cta',
  'header-help-menu__cta',
  'header-help-menu__cta--primary',
  'header-help-menu__cta--secondary',
  'header-help-menu__section',
  'header-help-menu__section-title',
  'header-help-menu__item',
  'header-help-menu__badge',
  'header-help-menu__status-card',
  'header-help-menu__status-card--upsell',
  'header-help-menu__status-card--active',
  'header-avatar',
  'header-avatar__initials',
  'header-stats-bar',
  'header-stats-bar__inner',
  'stat-pill',
  'stat-pill__value',
  'stat-pill__value--danger',
  'stat-pill__label',
  'app-header__legacy-status',
  'status-indicator',
  'status-indicator__dot',
  'status-indicator__dot--ok',
  'status-indicator__dot--danger',
  'app-header__date',
]);

export const HEADER_ACTIONS = Object.freeze({
  goAlertas: 'go-alertas',
  toggleHelpMenu: 'toggle-help-menu',
  goOrcamentos: 'go-orcamentos',
  openPmocModal: 'open-pmoc-modal',
  openPmocInfo: 'open-pmoc-info',
  openUpgrade: 'open-upgrade',
  openProfile: 'open-profile',
  helpOpenTutorial: 'help-open-tutorial',
  helpScoreInfo: 'help-score-info',
  helpSupport: 'help-support',
  helpFeedback: 'help-feedback',
});

export const HEADER_NAV_TARGETS = Object.freeze({
  registro: 'registro',
  clientes: 'clientes',
});

export const HEADER_DATA_ATTRIBUTES = Object.freeze([
  'data-action',
  'data-nav',
  'data-tier',
  'data-plan',
  'data-has-alerts',
]);
